### PR TITLE
Set moon variable to a default value earlier in the code

### PR DESCRIPTION
**Pull request by nickriley21**
Attempting to fix an issue that was causing problems with the moon variable in SkyStats.py

### CODE REVIEW

**Comment by teuben** [comment]
this one is running now, seems to be much less verbose :-)     will check out the results later. And of course curious in the speed improvement.

**Comment by nickriley21** [comment]
Sounds good, exciting!

**Comment by teuben** [comment]
alas, there was no time difference. Both took 90 mins.

**Comment by nickriley21** [comment]
That is extremely strange. When I run the script on my computer when it is calculating it for every image, for one night I get ~3 minutes. When I just calculate the one for the image it would be less than a minute.

image

The following is what I get when I only calculate it on the middle image.

image

Notice the time and CPU usage and that all of the other stats seem to be the same except for obviously the moon calculation. Any ideas why it isn't getting the same time reduction on yours?

**Comment by nickriley21** [comment]
The first image in the previous comment is when I run it calculating on every image.

**Pull request merged**
