### PR TITLE
Moon Phase Single Calculation

### PR DESCRIPTION
**Pull request by nickriley21**
Changed SkyStats.py to now only calculate the moon phase once on the middle image.

### CODE REVIEW

**Comment by teuben** [comment]
are you sure it's working. I got this when I ran the october month:

 Sun Nov 21 19:19:30 EST 2021 ==================================== working on ./2021-10-01 
Found 2004
Traceback (most recent call last):
  File "/n/astromake/opt/allsky/pyASC/ASC//SkyStats.py", line 74, in <module>
    middle_moon = my_moon(sys.argv[(len(sys.argv)+2)//2], True, box, -1.0)[3]
  File "/n/astromake/opt/allsky/pyASC/ASC//SkyStats.py", line 65, in my_moon
    return (t,np.median(dc),exp,moon,ffile)
UnboundLocalError: local variable 'moon' referenced before assignment
Command exited with non-zero status 1

**Comment by teuben** [comment]
btw, the whole october month with full moon calculations took about 90 mins.

**Comment by nickriley21** [comment]
Interesting, I did not get that error when running it on my end. I'll try to set moon to some default value earlier in the code.

**Comment by nickriley21** [comment]
okay, I created another pull request, this hopefully will fix the issue, not sure why it isn't giving that error on my end. Are different versions of python being a problem again?

**Pull request merged**
